import { ProgramFicha } from '../types';

export const INITIAL_FICHAS: ProgramFicha[] = [
  {
    name: "Buenos Días Bayamo",
    schedule: "7:02 AM - 8:58 AM",
    duration: "116 min",
    frequency: "Lunes a Sábado",
    func: "Divulgativa",
    music_cuban: "85 %",
    music_foreign: "15 %",
    group: "Variados",
    form: "Revista de variedades",
    complexity: "Muy Complejo",
    theme: "Varios generales",
    target: "Familia",
    times: { music: "24 min", info: "89 min", propaganda: "3 min" },
    startDate: "20 de Octubre de 1997",
    emissionType: "Vivo",
    literarySupport: "Guión: Menos Complejo, no escenificado. Costo desde $120.00 hasta $300.00.\nColaboración: Texto para comparecencia de especialista (Medicina general) los miércoles. Costo desde $200.00 hasta $2000.00.",
    objective: "Divulgación de temas y contenidos que resulten de utilidad a la población bayamesa.",
    profile: "Programa a dos voces, que presentan y desarrollan el tema, las secciones, además de los boletines y el resumen informativo. Cuenta con una línea temática central, y a ella tributan los distintos segmentos del programa. Puede contar con la participación de especialistas de distintas instituciones con primacía de Salud Pública, Higiene y Epidemiología, Centro de Prevención ITS, Dirección de Trabajo y Seguridad Social, Cruz Roja, Dirección Municipal de Cultura, Dirección Municipal de Justicia; y otras instituciones, que informarán contenidos relacionados con sus sectores, además de representantes de las organizaciones de masas. La música estará, siempre que sea posible, en función del tema que se aborda con marcado énfasis en los autores de Bayamo y la provincia. Utiliza propaganda directa e indirecta.\nIncluye 3 boletines de noticias (07:03, 07:30, 08:00) y un resumen informativo (08:50).\nLos martes y jueves, a las 07:10 se encadena al sistema nacional de la Radio Cubana para trasmitir el programa Chapeando bajito.\nInserta elementos de facilitación social importantes para la audiencia bayamesa (07:12) (30 min) Incluye intervenciones de especialistas. LUNES: Trabajo y Seguridad Social; MIÉRCOLES: Medicina general.",
    sections: [
      { name: "Un día como hoy en la historia", schedule: "Diaria (07:06)", duration: "1 min", description: "Segmento para la difusión de efemérides que se conmemoran cada jornada, primacía de los acontecimientos ocurridos en el municipio." },
      { name: "Sección Infantil", schedule: "Diario (07:07)", duration: "5 min", description: "Radia una narración, leyenda, historia, cuentos, adivinanzas y trabalenguas con intención educativa. Incluye un musical infantil." },
      { name: "Pregunta de participación", schedule: "Diaria (08:03)", duration: "5 min", description: "Da a conocer la pregunta y a las 8:27 se complace al ganador y se da una nota sobre la respuesta" },
      { name: "Sección deportiva (Boletín)", schedule: "Diaria (08:15)", duration: "5 min", description: "" },
      { name: "Este mundo nuestro", schedule: "Diaria (08:30)", duration: "3 min", description: "Se ofrecen curiosidades de temas generales." },
      { name: "Sobre el lenguaje", schedule: "Diaria (08:35)", duration: "3 min", description: "Se habla sobre palabras empleadas en el programa que pueden ofrecer significados complejos u otros temas relacionados con lenguaje." },
      { name: "De la Ciencia y la Técnica", schedule: "Diaria (08:43)", duration: "3 min", description: "Ofrece una caracterización de un elemento de ciencia y técnica relacionado con el tema." }
    ]
  },
  {
    name: "La Cumbancha",
    schedule: "9:00 AM - 9:58 AM",
    duration: "58 min",
    frequency: "Lunes a Sábado",
    func: "Recreativa",
    music_cuban: "85 %",
    music_foreign: "15 %",
    group: "Musicales",
    form: "Musical variado",
    complexity: "Complejo",
    theme: "Música popular cubana y/o extranjera",
    target: "Familia",
    times: { music: "49 min", info: "8 min", propaganda: "1 min" },
    startDate: "05 de Julio de 2010",
    emissionType: "Vivo",
    literarySupport: "Guión: Guión técnico.",
    objective: "Recrear a la audiencia bayamesa con música adecuada a sus gustos y preferencias.",
    profile: "Programa a una voz que anuncia música variada en géneros, estilos, épocas, y acredita los musicales y puede ofrecer breves informaciones sobre los mismos. El programa promueve música popular. Se puede realizar desde exteriores siempre con propuestas sustentadas en la música.\nPodrán realizarse concursos sobre aspectos musicales y comparecer divulgadores de instituciones musicales para brindar información y puede incluir entrevistas con músicos locales o del país para promocionar su música. Se ofrecen saludos, felicitaciones y reportes de sintonía enviados por los oyentes a través del correo o vía telefónica al programa, reportes de sintonía y se emplean los recursos sonoros del medio, así como la propaganda directa e indirecta.\nAlgunos Spots salen en voces de humoristas.",
    sections: []
  },
  {
    name: "Todos en Casa",
    schedule: "10:00 AM - 10:58 AM",
    duration: "58 min",
    frequency: "Lunes a Viernes",
    func: "Orientación",
    music_cuban: "85 %",
    music_foreign: "15 %",
    group: "Variados",
    form: "Revista de variedades",
    complexity: "Muy Complejo",
    theme: "Varios generales",
    target: "Familia",
    times: { music: "20 min", info: "36 min", propaganda: "2 min" },
    startDate: "05 de Julio de 2010",
    emissionType: "Vivo",
    literarySupport: "Guión: Menos Complejo, no escenificado. Costo desde $90.00 hasta $200.00.",
    objective: "Fortalecer un sistema de valores hábitos y estilos de vida en la audiencia bayamesa en correspondencia con los principios de la sociedad cubana.",
    profile: "Programa a una voz que en tono conversacional introduce y desarrolla el tema y los contenidos a tratar, anuncia y acredita los musicales, así como las distintas secciones relacionadas con el tema central y acredita los musicales. Utiliza los distintos recursos sonoros del lenguaje radial y propaganda directa e indirecta.",
    sections: [
      { name: "Sin fórmulas mágicas", schedule: "Diaria (10:12)", duration: "6 min", description: "Se explica una receta de cocina, se aconseja o recomienda según el tema central; en ocasiones se brindan propiedades de los ingredientes." },
      { name: "Lo bello también se lleva por fuera", schedule: "Diaria (10:28)", duration: "4 min", description: "Se brindan consejos de belleza para el cutis, el cabello o cualquier parte del cuerpo. También se dan recetas caseras ya sean para féminas u hombres." },
      { name: "La propia música", schedule: "Diaria (10:37)", duration: "5 min", description: "Es un ejercicio de relajación, el musical es escogido con ese propósito." },
      { name: "Prospecto radial", schedule: "Diaria (10:46)", duration: "2 min", description: "Como su nombre lo indica se habla sobre un medicamento o planta medicinal y se habla de sus usos o contraindicaciones." },
      { name: "Y algo más", schedule: "Diaria (10:51)", duration: "2 min", description: "Se conversa sobre la educación formal y otra variedad de temas relacionados con las problemáticas de la vida cotidiana." },
      { name: "Para mañana", schedule: "Diaria (10:53)", duration: "2 min", description: "Ofrece un adelanto sobre lo que ocurrirá al día siguiente en el programa." }
    ]
  },
  {
    name: "RCM Noticias",
    schedule: "11:00 AM - 11:13 AM",
    duration: "13 min",
    frequency: "Lunes a Sábado",
    func: "Informativa",
    music_cuban: "No especifica",
    music_foreign: "No especifica",
    group: "Informativos",
    form: "Noticiero Estelar",
    complexity: "Muy Complejo",
    theme: "Varios generales",
    target: "Adulto",
    times: { music: "0 min", info: "13 min", propaganda: "0 min" },
    startDate: "11 de Octubre de 2010",
    emissionType: "Vivo",
    literarySupport: "Guión: Guión Técnico.",
    objective: "Informar a la audiencia bayamesa sobre el acontecer noticioso del municipio, Granma, Cuba y el Mundo.",
    profile: "Programa a dos voces, que presentan los trabajos periodísticos y secciones. Pueden participar corresponsales que brinden informaciones de instituciones y comunidades y un narrador comentarista deportivo que brinda informaciones del acontecer deportivo.\nLas informaciones son fundamentalmente del municipio, aunque se incluyan las de mayor relevancia del acontecer provincial, nacional e internacional. Los sábados hace las previsiones de lo que será noticia la próxima semana. Utiliza los recursos sonoros del medio radiofónico y se apoya en autopromociones.",
    sections: []
  },
  {
    name: "Arte Bayamo",
    schedule: "11:15 AM - 11:58 AM",
    duration: "43 min",
    frequency: "Lunes a Viernes",
    func: "Cultural",
    music_cuban: "85 %",
    music_foreign: "15 %",
    group: "Variados",
    form: "Programa de variedades",
    complexity: "Complejo",
    theme: "Cultura y Arte",
    target: "Adulto",
    times: { music: "16 min", info: "26 min", propaganda: "1 min" },
    startDate: "05 de Julio de 2010",
    emissionType: "Vivo",
    literarySupport: "Guión: Menos Complejo, no escenificado. Costo desde $90.00 hasta $200.00.",
    objective: "Fomentar valores y reafirmar otros, en relación con los logros y aspiraciones espirituales de la audiencia bayamesa.",
    profile: "Espacio a una voz que presenta y desarrolla el tema, realiza entrevistas y comentarios. Incluye invitados, siempre que el contenido lo necesite. Enfoca cuestiones generales de la cultura bayamesa y su proyección hacia el plano nacional e Internacional. Diariamente el programa dedica su emisión a una manifestación del arte: LUNES: Audiovisuales, en dependencia de las necesidades del programa; MARTES: Artes Plásticas; MIÉRCOLES: Literatura; JUEVES: Música; VIERNES: Artes escénicas. El programa circunstancialmente puede relacionarse con eventos culturales que se desarrollen en la ciudad.\nEl programa puede utilizar entrevistas, comentarios e informaciones, que estén o no en función del tema central. Tiene un diseño sonoro acorde a las características del programa. Conjuga todos los elementos técnicos artísticos del medio radial. Este espacio se puede realizar desde exteriores en instituciones o comunidades donde se desarrollen actividades culturales. La música estará en función del texto siempre que sea posible. Incluye propaganda directa e indirecta.",
    sections: [
      { name: "Sumario", schedule: "Diaria (11:16)", duration: "2 min", description: "Segmento donde se dan a conocer los temas y secciones que conformarán el guión de esa emisión." },
      { name: "En taquilla", schedule: "Diaria (11:18)", duration: "2-3 min", description: "Promueve las acciones de las instituciones culturales bayamesas, significando las relaciones con las artes visuales, el teatro y la danza." },
      { name: "Juego de espejos", schedule: "Diaria (11:25)", duration: "3 min", description: "Se dedica a la crítica cultural, donde se comenta un trabajo publicado en alguna revista especializada en el tema del día, y también puede darse el caso que sea un comentario del propio autor del guión." },
      { name: "Página suelta", schedule: "Diaria (11:30)", duration: "4 min", description: "Momento para dar a conocer convocatorias a eventos, concurso u otros eventos de carácter cultural tanto local, nacional como internacional." },
      { name: "Epílogo", schedule: "Diaria (11:53)", duration: "1 min", description: "Resumen de todo lo acontecido en la emisión." },
      { name: "Contraportada", schedule: "Diaria (11:54)", duration: "1 min", description: "Es el adelanto de lo que ocurrirá en la próxima emisión y puede incluir informaciones de última hora." }
    ]
  },
  {
    name: "Parada Joven",
    schedule: "12:30 PM - 12:58 PM",
    duration: "28 min",
    frequency: "Lunes a Viernes",
    func: "Orientación",
    music_cuban: "85 %",
    music_foreign: "15 %",
    group: "Variados",
    form: "Programa de variedades",
    complexity: "Complejo",
    theme: "Varios generales",
    target: "Juvenil",
    times: { music: "12 min", info: "15 min", propaganda: "1 min" },
    startDate: "05 de Julio de 2010",
    emissionType: "Vivo",
    literarySupport: "Guión: Menos Complejo, no escenificado. Costo desde $70.00 hasta $140.00.\nColaboración: Texto para comparecencia de especialista (Psicología) SÁBADO. Costo desde $200.00 hasta $2000.00.",
    objective: "Favorece en la audiencia juvenil bayamesa un adecuado sistema de valores y actitudes en correspondencia con los principios de la sociedad cubana.",
    profile: "Programa a una voz, que en tono dinámico, introduce y desarrolla un tema relacionado con la formación integral de los Jóvenes. Se divulga la música cubana y extranjera, preferentemente los temas actuales de todos los géneros y formatos. Los sábados se realiza una emisión especial con la presencia de un especialista en Sicología que ayuda a despejar los temas y dudas de los oyentes que son atendidos durante la semana.",
    sections: [
      { name: "Parada de película", schedule: "Lunes y jueves (12:50)", duration: "", description: "Esta sección promociona series y películas que transmitirá la televisión cubana durante la semana." },
      { name: "Curiosidades", schedule: "Lunes a viernes (12:45)", duration: "2 min", description: "Se ofrecen curiosidades de este mundo nuestro." },
      { name: "Parada Cultural", schedule: "Miércoles (12:50)", duration: "2 min", description: "Esta sección ofrece informaciones culturales de interés para los jóvenes, así como eventos y convocatorias culturales." },
      { name: "Parada De Ciencia y Técnica", schedule: "Martes y viernes (12:50)", duration: "2 min", description: "Esta sección ofrece informaciones sobre adelantos y descubrimientos de la ciencia y la técnica." },
      { name: "Lo más escuchado", schedule: "Sábado (12:50)", duration: "6 min", description: "Esta sección ofrece los tres musicales de las últimas producciones destinadas a adolescentes y jóvenes." }
    ]
  },
  {
    name: "Hablando con Juana",
    schedule: "1:30 PM - 2:58 PM",
    duration: "88 min",
    frequency: "Lunes a Viernes",
    func: "Orientación",
    music_cuban: "85 %",
    music_foreign: "15 %",
    group: "Variados",
    form: "Revista de variedades",
    complexity: "Muy Complejo",
    theme: "Variados generales",
    target: "Adulto",
    times: { music: "25 min", info: "58 min", propaganda: "5 min" },
    startDate: "4 de marzo de 2024",
    emissionType: "Vivo",
    literarySupport: "Guión: Muy Complejo no escenificado. Costo desde $350.00 hasta $700.00.\nColaboración: Colaboración periodística (ENCUESTA) Semanal. Costo desde $50.00 hasta $2000.00.",
    objective: "Reafirma valores, actitudes y modelos de conducta en la audiencia, a partir del tratamiento de experiencias de vida sobre temas de diversa índole, que inciden en la vida de los oyentes.",
    profile: "Programa a dos voces que llevan diferentes momentos del espacio. Todo gira en torno a Juana, una vecina perspicaz que sabe la vida de todos, pero que, además, conoce también de política, cultura, deportes y, muy importante, de cuanto acontecimiento de relevancia y transformación ocurre en Bayamo.\nEl programa cuenta con un tema central que surge a partir de que Juana le comenta a uno de los locutores sobre una persona o una comunidad que tiene un conflicto del cuál no sabe cómo salir. Este conflicto es aportado por el guionista como resultado de una investigación previa y es expuesto por sus protagonistas a modo de confesión, planteamiento y petición de consejo y/o ayuda, para lo cual se cuenta con la presentación del caso por la locutora o la participación directa de personas de la comunidad. Para abordarlo y llegar a conclusiones finales, pueden comparecer especialistas, administrativos o personalidades coordinadas por el guionista, con los que se abordarán las diferentes aristas del tema.\nA lo largo del programa, se interactúa contantemente con las redes sociales y se puede insertar uno o varios trabajos periodísticos sobre el tema central, a solicitud del guionista. De ahí, deriva una segunda parte del programa, que pone en perspectiva otra arista del tema, a partir de un nuevo caso, surgido de la interacción con el público o suministrado por el guionista.\nIncluye un Boletín informativo a las 14:30 (3 minutos).\nSon varias secciones que redondean la vocación \"sabelotodo\" de Juana, a partir de informaciones, entrevistas y comentarios, que aportan datos y contexto sobre diversos temas de interés y que están \"en boca de todos\", en las redes o en la comunidad.",
    sections: [
      { name: "Entérate, vecino", schedule: "Diaria (13:35)", duration: "7 min", description: "Ofrece información sobre lugares, eventos, procesos y actividades que ocurren en los barrios. Visibiliza la labor de proyectos, cultores, personajes y líderes comunitarios con experiencias aportadoras en este sentido." },
      { name: "Historias cotidianas", schedule: "Diaria (13:45)", duration: "4 min", description: "Presenta una historia de vida o experiencia personal que da pie al tratamiento del tema central." },
      { name: "¿Y qué tú crees?", schedule: "Diaria (13:50)", duration: "3 min", description: "Se nutre de entrevistas realizadas a las personas en lugares significativos de la ciudad, sobre el tema que se aborda en el programa." },
      { name: "El que sabe, sabe", schedule: "Diaria (14:00)", duration: "8 min", description: "Se basa en la opinión experta sobre el tema que se aborda." },
      { name: "Polémica en las redes", schedule: "Diaria (14:20)", duration: "5 min", description: "Aborda asuntos de notoriedad que son muy comentados en redes sociales y se relacionan con el tema central." },
      { name: "Versiones encontradas", schedule: "Diaria (14:30)", duration: "5 min", description: "Ofrece una nueva mirada, opuesta o alternativa, al tema central tal y como es planteado inicialmente." },
      { name: "De todo un poco", schedule: "Diaria (14:45)", duration: "5 min", description: "Sugiere obras del arte y la literatura relacionadas con el tema abordado, da a conocer anécdotas y datos curiosos sobre artistas, escritores o grandes personalidades." }
    ]
  },
  {
    name: "Alba y Crisol",
    schedule: "7:30 AM - 7:43 AM",
    duration: "13 min",
    frequency: "Domingo",
    func: "Cultural",
    music_cuban: "No especifica",
    music_foreign: "No especifica",
    group: "Variados",
    form: "Charla expositiva",
    complexity: "Complejo",
    theme: "Historia de Cuba",
    target: "General",
    times: { music: "0 min", info: "13 min", propaganda: "0 min" },
    startDate: "1 de Julio de 2019",
    emissionType: "Grabado",
    literarySupport: "Guión: Complejo, no escenificado. Costo desde $60.00 hasta $150.00.",
    objective: "Promover valores y reafirmar el conocimiento de otros relacionados con la historia de Bayamo, en función de mejorar el acervo cultural del ser humano.",
    profile: "Programa a una voz que propone y desarrolla un tema histórico referido al papel de los bayameses y Bayamo en la historia patria. Se exponen y describen en tono coloquial y reflexivo hechos históricos relacionados con Bayamo, desde los orígenes hasta la actualidad. Puede cerrar con un brebe fragmento musical que apoye el tema. Utiliza los recursos sonoros del medio. Puede incluir un invitado que exponga el tema.",
    sections: []
  },
  {
    name: "Coloreando Melodías",
    schedule: "9:30 AM - 9:43 AM",
    duration: "13 min",
    frequency: "Domingo",
    func: "Orientación",
    music_cuban: "100 %",
    music_foreign: "No especifica",
    group: "Variados",
    form: "Programa de Variedades",
    complexity: "Muy Complejo",
    theme: "Socio culturales",
    target: "Infantil",
    times: { music: "5 min", info: "8 min", propaganda: "0 min" },
    startDate: "1 de Julio de 2019",
    emissionType: "Grabado",
    literarySupport: "Guión: Complejo, no escenificado. Costo desde $60.00 hasta $150.00.",
    objective: "Reafirmar, en los niños y niñas de un sistema de valores, actitudes y modelos de conducta positivos en consecuencia con los principios de la sociedad, preservándolos y fortaleciéndolos.",
    profile: "Programa en que niños, una locutora, y una actriz que interpreta un personaje fantástico, en forma coloquial desarrollan temas socioculturales y educativos, adecuados al destinatario infantil, ofrecen saludos, felicitaciones, pueden promover concursos de la OPJM y sobre historia local y anunciar los ganadores, así como breves narraciones de cuentos. Ofrecen y acreditan los musicales infantiles. Se prioriza la música de Bayamo, Granma y de Cuba. Por excepción se puede usar música infantil latinoamericana. Se apoya en los recursos sonoros del lenguaje radial.",
    sections: []
  },
  {
    name: "Cómplices",
    schedule: "7:02 AM - 9:58 AM",
    duration: "176 min",
    frequency: "Domingos",
    func: "Orientación",
    music_cuban: "85 %",
    music_foreign: "15 %",
    group: "Variado",
    form: "Programa de variedades",
    complexity: "Complejo",
    theme: "Varios generales",
    target: "Familia",
    times: { music: "83 min", info: "90 min", propaganda: "3 min" },
    startDate: "9 de julio de 2023",
    emissionType: "Vivo",
    literarySupport: "Guión: Menos complejo. Costo desde $120.00 hasta $300.00.",
    objective: "Fortalecer en la audiencia bayamesa, un sistema de valores, actitudes y modelos de conducta positivos en consecuencia con los principios de la sociedad.",
    profile: "Programa a una voz que presenta y desarrolla las diferentes páginas y secciones del programa. El programa cuenta con 8 páginas, cada una con una temática diferente, dos boletines informativos, 2 segmentos de facilitación social, y una sección del recuerdo.\nLos temas que se abordan son destinados a la familia en general, aunque existe uno que va dirigido exclusivamente a las personas de la tercera edad.\nSe propicia la interacción oyente-colectivo realizador por medio de una pregunta de participación relacionada con el tema de la primera página, y una competencia musical entre dos intérpretes, de la cual se radia un minirecital. Se insertan dentro de este programa los espacios grabados Alba y Crisol (7:30) y Coloreando melodías (9:30).\nUtiliza todos los recursos sonoros del medio, así como propaganda directa e indirecta.",
    sections: []
  },
  {
    name: "Estación 95.3",
    schedule: "10:00 AM - 12:58 PM",
    duration: "178 min",
    frequency: "Domingo",
    func: "Recreativa",
    music_cuban: "85 %",
    music_foreign: "15 %",
    group: "Musicales",
    form: "Musical Variado",
    complexity: "Complejo",
    theme: "Música Popular Cubana y Extranjera",
    target: "Jóvenes",
    times: { music: "142 min", info: "30 min", propaganda: "6 min" },
    startDate: "7 de enero de 2024",
    emissionType: "Vivo",
    literarySupport: "Guión: Menos Complejo, no escenificado. Costo desde $120.00 hasta $300.00.",
    objective: "Recrear a la audiencia con los más altos valores de la música bayamesa, cubana y universal de manera atractiva para los oyentes, con énfasis en el público joven.",
    profile: "El programa iniciará con los adelantos de lo que acontecerá en la emisión, el invitado, el contenido de las secciones y la música que utilizará. Lo anterior no podrá exceder los tres minutos.\nSe presentará el programa, un musical y acto seguido la sección Dial Sonero, posteriormente hará un espacio para llamadas telefónicas, solicitando música o saludos. Luego transcurrirá Estación Mundial y a continuación el Boletín informativo. Así trascurrirá la primera hora de emisión.\nDurante la segunda hora, el espacio Mano a Mano, otro momento para saludos, felicitaciones y solicitud de canciones, además de las secciones La Farándula se mueve y Mucho Flow. También en esta hora los oyentes podrán comenzar a enviar mensajes de reconocimiento para el entrevistado.\nEn la tercera hora se presentará la cartelera cultural para la semana y se realizará la entrevista con el invitado. El programa concluye con un miniconcierto de este músico.",
    sections: [
      { name: "Dial Sonero", schedule: "", duration: "", description: "Es la primera sección, con el objetivo de promover la música popular cubana a partir de sus principales exponentes y su trabajo en la actualidad. Se privilegiarán los temas actuales que resalten la identidad nacional. Tiene una descripción de la orquesta o intérprete y 2 temas musicales." },
      { name: "Estación Mundial", schedule: "", duration: "", description: "Ilustrará el quehacer de músicos internacionales que estén en el hit parade, con una obra relevante y de preferencia en los oyentes. Posee 2 números musicales." },
      { name: "Mano a Mano", schedule: "", duration: "", description: "Espacio para disfrutar de la música de Dos agrupaciones o solistas del municipio. Iniciará con una breve reseña de ambos intérpretes y Dos canciones de cada exponente." },
      { name: "La Farándula se mueve", schedule: "", duration: "", description: "Boletín de noticias relacionadas con el acontecer de la industria musical y los principales eventos en Cuba y el mundo." },
      { name: "Mucho Flow", schedule: "", duration: "", description: "Espacio para conocer sobre los exponentes de la música urbana." },
      { name: "Qué hay pá hoy", schedule: "", duration: "", description: "Sección para conocer las principales actividades que se desarrollarán en el municipio." },
      { name: "De Bayamo para el Mundo", schedule: "", duration: "", description: "Colofón del programa, con la entrevista a un artista bayamés invitado." }
    ]
  },
  {
    name: "Palco de domingo",
    schedule: "1:30 PM - 2:58 PM",
    duration: "88 min",
    frequency: "Domingo",
    func: "Cultural",
    music_cuban: "85 %",
    music_foreign: "15 %",
    group: "Variados",
    form: "Revista de perfil cultural",
    complexity: "Muy Complejo",
    theme: "Cultura bayamesa",
    target: "General",
    times: { music: "25 min", info: "58 min", propaganda: "5 min" },
    startDate: "10 de marzo de 2024",
    emissionType: "Vivo",
    literarySupport: "Guión: Muy Complejo no escenificado. Costo desde $350.00 hasta $700.00.\nColaboración: Texto para comparecencia de especialista y/o experto (Música, Artes Plásticas, Literatura, Artes Escénicas) Semanal. Costo desde $200.00 hasta $2000.00.",
    objective: "Desarrollo de valores estéticos en la audiencia, así como a su acervo cultural, a través del enaltecimiento de la obra de artistas, escritores y cultores bayameses.",
    profile: "El programa cuenta con una voz que conduce todo el espacio, que en determinado momento del espacio interactúa con un personaje peculiar de los escenarios bayameses, \"Carmita Bravo\", aportadora sus recuerdos y valoraciones. Desarrolla un tema central en la mayor parte del tiempo, enriquecido con secciones que abordan diferentes aristas o aportan conocimientos e información sobre arte y literatura.\nIncluye un Boletín Informativo a las 14:30 (3 minutos).\nEl formato concibe la ambientación en un escenario imaginario de Bayamo, en cuyos palcos se disponen a disfrutar del arte, pintura, cine, literatura, teatro, danza, música, artistas y obras de arte, eventos culturales desarrollados en Bayamo, el locutor los invitados y los oyentes. A partir de esta premisa, transcurren los diferentes segmentos del programa, cada uno dedicado a una manifestación artística o a una arista que le aporte conocimientos a la audiencia y contribuya con su formación estética. La locución es un elemento determinante, pues debe poseer la preparación suficiente para abordar y comentar los temas e interactuar con los invitados, a la vez que debe ser fresca y propiciadora de la atención de los oyentes.",
    sections: [
      { name: "Agenda cultural", schedule: "13:35", duration: "5 min", description: "Ofrece información sobre eventos culturales que tendrán lugar la próxima semana." },
      { name: "Arte popular", schedule: "13:45", duration: "4 min", description: "Publica un reportaje sobre el tema abordado en el programa, cuenta con criterios de la audiencia, entrevistas a artistas y especialistas y breves comentarios." },
      { name: "Reto al espectador", schedule: "14:00", duration: "3 min", description: "Propone una pregunta de participación a la audiencia, relacionada con el tema abordado, y propicia los comentarios al respecto." },
      { name: "Asiento reservado", schedule: "14:15", duration: "5 min", description: "Se basa en la opinión experta sobre el tema que se aborda, cuenta con la participación de un especialista o artistas invitados." },
      { name: "La obra y el artista", schedule: "14:35", duration: "5 min", description: "Ofrece reseñas sobre obras de arte, relacionadas con el tema abordado, así como datos del artista." },
      { name: "Legado bayamés", schedule: "14:45", duration: "4 min", description: "Enaltece un hecho histórico, personalidad, obra de arte antológica o tradición propia de Bayamo." }
    ]
  }
];
